FROM node:20-alpine

WORKDIR /app

# Installation des dépendances
COPY frontend/package*.json ./
RUN npm install

# Copie du code source
COPY frontend/ .

# Construction de l'application
RUN npm run build

# Installation du serveur statique
RUN npm install -g serve

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
