FROM golang:1.23-rc-alpine3.19

WORKDIR /app

# Installation des dépendances de build
RUN apk add --no-cache gcc musl-dev

# Copie des fichiers go.mod et go.sum
COPY go.mod go.sum ./
RUN go mod download

# Copie du reste du code source
COPY . .

# Construction de l'application
RUN go build -o server ./cmd/server

EXPOSE 8080

CMD ["./server"]
